{
 "title": "JUNO Node by Cumulo",
 "description": "This dashboard provides real-time monitoring of a full **JUNO node** with optional validator capabilities. It includes metrics for:\n\n- 🔄 Synchronization status (`sync_*`)\n- 🧠 Node identity and version info\n- 🔐 Validator attestation tracking (epochs, slots, confirmations)\n- 📊 Epoch progress and last attestation delay\n- 🌐 RPC and HTTP request activity\n- 🧮 Resource usage (memory, uptime)\n\nBuilt by **Cumulo Pro** to help operators visualize performance, detect issues, and maintain reliable node operations across the Starknet network.\n\nRecommended for use with **Prometheus** as data source. Fully compatible with `juno` metrics exposed via `/metrics` endpoint.\n",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)\n" } },
   { "name": "juno_version", "query": { "query": "query_result(juno_info)" } }
  ]
 },
 "panels": [
  { "title": "Juno node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/starknet.png\" alt=\"Logo\" style=\"height: 100px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>JUNO NODE</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n    <h6><a href=\"https://github.com/Cumulo-pro/starknet_tools/tree/main/juno#readme\">Dashboard docs</a></h6>\n</div>"
   }
  },
  {
   "title": "Sync height ",
   "type": "stat",
   "description": "Indicates the height of the most recent block that the node has successfully synced. If this number is lower than sync_best_known_block_number, the node is still catching up.",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_blockchain_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "description": "metric provides **static information about the Juno binary** currently running, typically used to expose metadata such as version",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "# Juno version\n\n<h3 style=\"white: blue; font-size: 36px; text-align: center;\">\n  ${juno_version}\n</h3>"
   }
  },
  {
   "title": "Best Known Block",
   "type": "stat",
   "description": "Represents the highest block number known to the node — essentially the latest height the network has reached according to this node.",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_best_known_block_number{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Blocks",
   "type": "gauge",
   "description": "A cumulative counter of blocks synchronized by the node since it started running.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_blocks{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SYNC STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A -  $B", "type": "math" }
   ]
  },
  {
   "title": "RPC http Requests",
   "type": "stat",
   "description": "This counter metric tracks the total number of HTTP requests received by the RPC server.\n\nIt is a high-level indicator of how much traffic the node is receiving via HTTP, without breaking it down by method or path.",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_http_requests{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Attestation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Current Epoch Height",
   "type": "stat",
   "description": "The total number of blocks that make up the current epoch.\nUseful to calculate expected validator duties per epoch. Should be consistent with protocol settings (e.g., 120 blocks per epoch).",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_attestation_current_epoch_length{job=\"JunoAttestation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch Starting Block",
   "type": "stat",
   "description": "The block number at which the current epoch began.\nHelps determine whether the validator is tracking the correct epoch boundaries. Should increase every current_epoch_length blocks.",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l1_height{job=\"$job\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Latest Block",
   "type": "stat",
   "description": "The most recent block observed by the validator on the Starknet network.\nMeasures whether the validator is up-to-date with Starknet’s latest blocks. Can be used to compare with assigned_block_number and detect delay or lag.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_attestation_starknet_latest_block_number{job=\"JunoAttestation\"}",
     "legendFormat": "Interval"
    }
   ]
  },
  {
   "title": "Sync Reorganisations",
   "type": "stat",
   "description": "Counts the total number of blockchain reorganizations (reorgs) detected by the node.\nPurpose:\nA value greater than 0 may indicate unstable peers, conflicting forks, or validator misbehavior. Frequent reorgs are a sign of poor consensus health.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_reorganisations{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch Assigned Block",
   "type": "stat",
   "description": "The specific block number in the current epoch for which the validator has been assigned an attestation responsibility.\nCritical for verifying validator duty assignment. You can compare this with the latest block number to alert if the attestation slot is missed.",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_attestation_current_epoch_assigned_block_number{job=\"JunoAttestation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch ID",
   "type": "stat",
   "description": "The identifier of the current epoch the validator is participating in. This value increments as the network advances epochs.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_attestation_current_epoch_id{job=\"JunoAttestation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestation Submitted Count",
   "type": "gauge",
   "description": "TThe total number of attestation messages the validator has submitted to the network since startup.\nUseful to track validator activity rate. Comparing this with attestation_confirmed_count helps detect failures or rejections.",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_attestation_attestation_submitted_count{job=\"JunoAttestation\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Attestation Confirmed Count",
   "type": "gauge",
   "description": "The total number of attestations submitted by the validator that have been confirmed on-chain since the validator process started.\nConfirms validator participation is being successfully recorded and accepted by the network.",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_attestation_attestation_confirmed_count{job=\"JunoAttestation\"}",
     "legendFormat": "{{matches_current}}"
    }
   ]
  },
  {
   "title": "Last Attestation Time",
   "type": "gauge",
   "description": "Unix timestamp of the most recent attestation successfully submitted by the validator.",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - validator_attestation_last_attestation_timestamp_seconds\r\n{job=\"JunoAttestation\"}",
     "legendFormat": "Number of transactions pending confirmation that have not yet been included in a block"
    }
   ]
  },
  {
   "title": "Attestation Uptime",
   "type": "gauge",
   "description": "This panel tracks the validator's attestation success rate by dividing the number of confirmed attestations by the number of epochs.",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(validator_attestation_attestation_confirmed_count / validator_attestation_current_epoch_id) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "system monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Process CPU Seconds Total",
   "type": "gauge",
   "description": "total CPU time, both user and system, consumed by the process since its start-up",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Process Virtual Memory Usage",
   "type": "stat",
   "description": "Total amount of virtual memory used by the process in bytes",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Process Resident Memory Usage",
   "type": "stat",
   "description": "Sze of the resident memory used by the process, expressed in bytes",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of Garbage Collection Pauses in Go",
   "type": "timeseries",
   "description": "This metric provides a summary of the duration of rubbish collection cycle pauses in the Go runtime environment.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"$job\"}",
     "legendFormat": "Seconds Sum"
    }
   ]
  }
 ]
}